Step 4 change (Using C++ and Pybind)
kliu3638/learnsomething pull request #6
Opened 2023-10-12 00:53 UTC by kliu3638

![image](https://github.com/kliu3638/learnsomething/assets/115598673/5d0c0ad1-9b8b-4215-a93a-d8a2180f9d00)

2023-10-12 16:54 UTC, minnce requested changes
speed is good, just rebase so it can merge

2023-10-12 17:19 UTC, echavemann commented
rebase is not the problem

2023-10-12 17:19 UTC, echavemann commented
just need to resolve merge conflict

2023-10-12 17:19 UTC, echavemann commented
@minnce we need to improve PR quality this is an issue

2023-10-12 17:21 UTC, echavemann requested changes

2023-10-12 17:21 UTC, echavemann commented on .vscode/c_cpp_properties.json
> +        {
please ignore .vscode

2023-10-12 17:21 UTC, echavemann commented on cpp/primeFactor.cpp
> +#include <unordered_set>
clean up unused imports

2023-10-12 17:21 UTC, echavemann commented on prime.py
> +    # # Sieve to get primes
delete commented code

2023-10-13 06:53 UTC, kliu3638 commented
Made changes accordingly.

2023-10-13 08:35 UTC, minnce approved these changes
looks good to me now!

2023-10-13 08:43 UTC, merged